retest

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -36,7 +36,6 @@ jobs:
     - name: Test with pylint
       run: |
         sudo apt install pylint -y
-        pylint -E app.py
-        if [ $? -ne 0 ]; then echo "Failure! - Python Errors Detected" && exit 1 fi
-        echo "Success! - No Python Errors Detected"
+        pylint -E app.py || echo "Failure - Pylint Status Code: $?" && exit 1
+        echo "Success! - Python Error Checks Passed"
 
