testing with pylint (#8)
* testing with pylint

* apt install pylint

* sudo apt install

* add success message

* fix if bash

* retest

* retest 2

* int fail

* updated actions with pylint

* python tests

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -12,7 +12,7 @@ on:
     types: [published]
 
 jobs:
-  build:
+  python-tests:
 
     runs-on: ubuntu-latest
 
@@ -34,4 +34,8 @@ jobs:
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     - name: Test with pylint
-      run: pytest -E app.py
+      run: |
+        sudo apt install pylint -y
+        pylint -E app.py || { echo "Failure! - Python Error Checks Failed - $?" ; exit 1; }
+        echo "Success! - Python Error Checks Passed"
+
